services:
  - type: web
    name: avela-api
    runtime: docker
    dockerfilePath: apps/api/Dockerfile
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PRIVY_APP_ID
        sync: false
      - key: PRIVY_APP_SECRET
        sync: false
      - key: XLAYER_RPC_URL
        value: https://rpc.xlayer.tech
      - key: PORT
        value: 3001
      - key: AVELA_VAULT_ADDRESS
        value: 0x3479183bcbcC3643fDb6a26C7215e602095C2086
      - key: AVELA_ROUTER_ADDRESS
        value: 0x6986CF2784f112bc1610ee743F33246d9C4B869B
      - key: SIGNER_PRIVATE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
